### ISSUE TITLE
Button IDs are invalid if the text contains spaces

### ISSUE THREAD

**Issue by bsyk** [PredixDev/px-modal#10]
When using px-modal and specifying Btn Modal Positive (or Negative) the supplied text is used for the label of the button and the ID of the button.

If this text contains spaces, the ID is not valid HTML.

![image](https://cloud.githubusercontent.com/assets/6765840/18976140/7dd60614-8664-11e6-8e82-149572942dc8.png)
![image](https://cloud.githubusercontent.com/assets/6765840/18976055/d1f9c6aa-8663-11e6-8aab-90b8ce37fd0c.png)

```
<button class="btn btn--primary style-scope px-modal" id="Continue With Fish" disabled="">Continue With Fish</button>
```

**Comment by nonmetalhail** [comment]
Pushed a fix in 1.3.1
