### ISSUE TITLE
px-modal opens on disabled button with fa icon

### ISSUE THREAD

**Issue by tejrajendran** [PredixDev/px-modal#11]
Hello,
Having some issues using px-modal in my polymer component. Please see attached code below. Clicking on the button does not open the modal, but clicking on the icon itself does. We could implement a workaround with template dom-if but would prefer another solution.
`<px-modal btn-modal-positive="Yes"  btn-modal-negative="Cancel" btn-modal-positive-clicked-event-name="onDelete" modal-heading="Remove Form" scrolling-disabled="true">
          <button class="btn btn--tertiary btn--icon modal-trigger" disabled><i class="fa fa-trash"></i></button>
          <p>Are you sure?</p>
        </px-modal>`

**Comment by runn-vermel** [comment]
I'm Sorry, I don't quite understand your issue - I understand that the Modal DOES open, but i'm not sure what does and doesn't work for you after that?

**Comment by randyaskin** [comment]
Here's a codepen illustrating the issue:
http://codepen.io/randyaskin/pen/vygXBx?&editors=1001

The button has the "disabled" flag, so clicking on the text/body of the button does NOT open the modal (was a typo above), but clicking on the font awesome icon DOES launch the modal.

**Comment by randyaskin** [comment]
@tejrajendran I didn't make any changes to px-modal (it doesn't actually care what the triggering element is) but I've updated px-buttons-design so that disabled buttons will not fire any pointer-events. Update to the latest version of buttons and see if you still have this issue with your modal. Thanks!
