### ISSUE TITLE
modal trigger does not work in Chrome.

### ISSUE THREAD

**Issue by ronaldsankey** [PredixDev/px-modal#13]
**Modal trigger does not work in Chrome.  It DOES work in I.E.11 and current Firefox.**

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
**Chrome --  Version 52.0.2743.116 (64-bit)**

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.

    <p><px-modal btn-modal-positive="SAVE" btn-modal-negative="CANCEL"
                modal-heading="Delay reasons configuration">
        <a href="javascript:void(0)" class="modal-trigger">Delay reasons configuration</a>
    <p> Insert component here! </p>
    </px-modal></p>

**Comment by randyaskin** [comment]
I've tested your code in Chrome 55 and Chrome 52, and the modal seems to work fine in both.
http://codepen.io/randyaskin/pen/apEaoK?&editors=1001

**Comment by ronaldsankey** [comment]
I did just verify that the component works from the Predix UI component page.  I am using it within an Angular 2 app, not sure if there is anything that might make a difference there.

**Comment by ronaldsankey** [comment]
Just an update that I didn't post earlier -- this issue happens when the px-modal component is directly in an Angular2 component.  If I pull it out into another polymer component and reference that from Angular, it works.

**Comment by randyaskin** [comment]
There's definitely some weirdness between Angular and Polymer. There are a few libraries that are supposed to help, including [one by Rob Dodson](https://github.com/robdodson/angular-custom-elements) (former GE, current Googler) though I think his is more ng1 vs ng2. Sounds like you found a workaround and we can close this?
