### ISSUE TITLE
Simplify API using content slots

### ISSUE THREAD

**Issue by randyaskin** [PredixDev/px-modal#15]
Instead of the complicated `btnModalPositiveEventName` etc properties, a simpler approach for the buttons and their states / behaviors may be to replace them with a second content slot for the footer of the modal and provide a method or event listener for closing the modal.

**Comment by laxika** [comment]
Can'T you provide an .open() and .close() functions for the modal? .modalButtonClicked() is far from trivial/intuitive.

**Comment by mdwragg** [comment]
Pull requests are always welcome.

**Comment by randyaskin** [comment]
@davidrleonard did this in the latest refactor by allowing properties (for simplicity) with override possible via content slots. @laxika 's concern also addressed, you can just set `opened` to true or false to achieve the same thing as `open()` or `close()`
