### ISSUE TITLE
Assumes font-awesome dependency. 

### ISSUE THREAD

**Issue by sachinkantipudi** [PredixDev/px-modal#18]
While doing bower-install px-modal component, it should also download font-awesome library as a dependency. Right now, it's not, because of which, my module bundling process is failing. Please fix it.

**Comment by randyaskin** [comment]
What version are you trying to use? We moved away from font-awesome in the latest major version of all Px components. Please refer to https://www.predix-ui.com/#/tools/version-finder

**Comment by sachinkantipudi** [comment]
Hi Randy, we're using the post-refresh version only ("px-modal": "https://github.com/PredixDev/px-modal.git#^2.0.3") for px-moal component, still reliance on font-awesome is there. If it assumes dependency, it has to install it, and it does not at the moment.

**Comment by randyaskin** [comment]
My bad, looks like the sass for this one hadn't rebuilt cleanly in a while. Try v2.0.4.
