### ISSUE TITLE
Need <slot> to work with Polymer 2.0

### ISSUE THREAD

**Issue by squidbe** [PredixDev/px-modal#20]
## Expected behavior and actual behavior:
Expected: HTML within &lt;px-modal&gt; tag should render
Actual: It doesn't render :-)

## Steps to reproduce the problem:
Use px-modal with polymer 2.x
Do something like this:
```
<px-modal btn-modal-positive="OK" 
          btn-modal-negative="Cancel">
    <p>Lorem ipsum...</p>
</px-modal>
```

Replacing &lt;content&gt; with &lt;slot&gt; in px-modal.html fixes the issue for me.

**Comment by davidrleonard** [comment]
I've pushed the `polymer2.0-preview` branch with this and other misc. Polymer 2.0 issues addressed.

https://github.com/PredixDev/px-modal/tree/polymer2.0-preview
