### ISSUE TITLE
Px-Modal loading twice issue

### ISSUE THREAD

**Issue by Priyanka1403** [PredixDev/px-modal#21]
# Px-modal opens 2 times when the page loads or when we navigate within the page after opening.
Same behavior can be checked on https://www.predix-ui.com/# also.
Steps:
1. Click on Open Modal.
2. Close it.
3. Navigate to some other link in the page from left side.
4. Come again to Modal page.
You will see the flicker of modal window.

**Comment by randyaskin** [comment]
Fixed in v2.0.6.
