### ISSUE TITLE
clicking outside modal(apart from gray area) closes the modal

### ISSUE THREAD

**Issue by Priyanka1403** [PredixDev/px-modal#22]
# We have a trigger for modal and it gets closed when we click somewhere apart from gray area in the page.

**Comment by randyaskin** [comment]
If you had followed the issue template, we would know what browser and operating system you're referring to, steps to reproduce, etc. The functionality you describe does not exist, the px-modal does not dismiss when a user clicks on the gray area, it can only be dismissed by clicking one of the buttons.

**Comment by Priyanka1403** [comment]
![untitled](https://user-images.githubusercontent.com/16699739/31597666-5119b7d0-b267-11e7-9cd1-0f8d92e8a508.png)

we have a left nav bar and top header, if we hover over there it closes. refer the screenshot

**Comment by randyaskin** [comment]
I still think this must be a customization of your application, as the *only* mechanism that px-modal has for hiding itself is if an element with class `modal-trigger` is tapped, or if the `modalButtonClicked` method is called on the px-modal. Does your application use app hub / pxh-chrome?
