### ISSUE TITLE
Adds unwanted inline overflow styles on html and body tag

### ISSUE THREAD

**Issue by jschlieber** [PredixDev/px-modal#23]
### Expected
When the modal is closed, the original state of the DOM (before the modal was opened) should be restored.

### Actual
When the modal is closed it sets `overflow: auto` inline styles on the `html` as well as on the `body` tag which can cause style conflicts and general issues with certain css normalizations, i.e. setting `overflow-y: scroll` on the `html` tag.

**Comment by randyaskin** [comment]
No longer the case in v3 of the modal.
