### ISSUE TITLE
Support Polymer v2 on 2.0.8

### ISSUE THREAD

**Issue by shinxi** [PredixDev/px-modal#25]
https://github.com/PredixDev/px-modal/blob/691096771e58934cbe791560fe290edcf799c421/px-modal.html#L53
It's still polymer v1, can we at least add a name so that it won't break polymer v2. E.g,
```
 <content select=".modal-trigger" name="modal-trigger"></content> 
```
I know we are working on [polymer2.0-preview-breaking-api](https://github.com/PredixDev/px-modal/blob/polymer2.0-preview-breaking-api/package.json), but it'll be no harm to support polymer v2 for current version.

**Comment by randyaskin** [comment]
I don't think that's correct, the actual tag itself changes from `<content select="x">` to `<slot name="x">` from Polymer 1 to 2, so just adding a name to the content tag still won't be picked up by the new version.

**Comment by shinxi** [comment]
Yes, you are right, it should be 
```jsx
 <slot name="modal-trigger"></slot> 
```
After this change, developers have to change from
```jsx
 <button className="btn btn--primary modal-trigger">Open Modal</button>
```
to
```jsx
 <button className="btn btn--primary" name="modal-trigger">Open Modal</button>
```

**Comment by randyaskin** [comment]
That's not the approach we've chosen to follow for the Predix components - use v3.0.0 for Polymer 2 hybrid component or continue using v2.0.8 with Polymer 1.
