### ISSUE TITLE
iron-fit-behavior is unlisted dependency

### ISSUE THREAD

**Issue by Bitty9** [PredixDev/px-modal#26]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:

performing bower install --save on px-modal and then using when we haven't installed iron-fit-behavior fails to render, not self contained

## Steps to reproduce the problem:

bower init;
bower install --save px-modal
create a skeleton index.html with an open px-modal
should see an error on open.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Any environment, px-modal version ^3.1.2, we are specifically using polymer-webpack-loader, but this issue should be separate from that plugin.

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by randyaskin** [comment]
Fixed in 3.1.3.
