### ISSUE TITLE
Scrolling in modal, should not trigger scrolling in the page.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-modal#28]
## Expected behavior and actual behavior:

If a modal has a vertical scrollbar, scrolling in the modal should not scroll the page underneath it.
This was seen during the new px-data-grid testing. Using iron-overlay could potentially prevent this.

## Environment:

Browser: Chrome
px-modal: 3.1.2

### Initial State:
![screen shot 2018-01-25 at 1 32 32 pm](https://user-images.githubusercontent.com/10835611/35414611-d16c62f6-01d7-11e8-99cd-a42dce4344b4.png)

### After vertical scroll in modal:
![screen shot 2018-01-25 at 1 32 45 pm](https://user-images.githubusercontent.com/10835611/35414637-dc311a7e-01d7-11e8-8f15-4a1ea37b2d10.png)

**Comment by randyaskin** [comment]
@davidrleonard fixed in v3.2.2.
