### ISSUE TITLE
Missing padding inside modal

### ISSUE THREAD

**Issue by sachinkantipudi** [PredixDev/px-modal#31]
## Expected behavior and actual behavior:
Expected: Padding inside opened modal
Actual: Missing padding, when modal has custom header and body

## Steps to reproduce the problem:
Open a modal by clicking on the trigger.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_): 
px-modal: 3.2.1, Chrome latest, Mac OSX

## Screenshots (_optional, but very helpful_):
<img width="485" alt="screen shot 2018-02-01 at 4 08 22 pm" src="https://user-images.githubusercontent.com/13139814/35710069-557bcd92-076a-11e8-8333-1cc2fdf16cfc.png">

**Comment by mdwragg** [comment]
As per the issue template. Can you provide us with a codepen/glitch/jsbin showing this behaviour? It makes things much easier for us to fix if we can quickly recreate the issue.

**Comment by randyaskin** [comment]
It seems you are using the `slot` features within modal. Like all light DOM slots in our components, they are completely flexible, and you are therefore responsible for styling the content yourself.

**Comment by sachinkantipudi** [comment]
Also, it looks like when modal has custom header and body (using `<div slot="header"></div>`), CSS is not right. In particular, CSS is missing for 
1) positive modal button enabled and disabled state.
2) header margin and style
3) padding of the modal body

**Comment by sachinkantipudi** [comment]
Oh I see, thank you Martin and Randy!! I will handle styling myself.
