### ISSUE TITLE
git readme is not updated, modalButtonClicked() not working anymore

### ISSUE THREAD

**Issue by nabila17785** [PredixDev/px-modal#35]
## Problem details:
In the examples section, it is mentioned to bring up a modal by using modalButtonClicked(), but it didn't work as the function is missing. I opened the px-modal code and found that we simply set this flag opened to show the modal, could you please update readme on git as it is misleading now.

## Versions:
Angular: 5
Polymer: 1.11.2
Browser: chrome
Operating System: Mac OS

**Comment by randyaskin** [comment]
Good spot, thank you. We usually focus on the [full API page](https://www.predix-ui.com/#/elements/px-modal) and sometimes forget about the README. :)
