### ISSUE TITLE
px-modal behaves abnormal with iron-list element, takes height/width of the parent rather than device/window

### ISSUE THREAD

**Issue by mshahidkhan** [PredixDev/px-modal#6]
px-modal behaves abnormal with iron-list element, takes height/width of the parent rather than device/window

Please try the below code 

`<iron-list items="[[mydata]]" as="item">
    <template>
        <div>
        <px-modal btn-modal-positive="Continue"
                      btn-modal-negative="Back"
                      modal-heading="Title">
                <button class="btn btn--primary modal-trigger">
                    <i class="fa fa-user"></i>
                </button>
            </px-modal>
        </div>
    </template>
</iron-list>`

**Comment by mshahidkhan** [comment]
<iron-list items="[[mydata]]" as="item">
            <template>
                <div>
                    <px-modal btn-modal-positive="Continue"
                              btn-modal-negative="Back"
                              modal-heading="Title">

                        <button class="btn btn--primary modal-trigger">
                            <i class="fa fa-user"></i>
                        </button>
                    </px-modal>
                </div>
            </template>
        </iron-list>

**Comment by jonniespratley** [comment]
Its the way the iron-list items are rendered. Im working on a pull request that enables you to put the trigger outside the modal, thus you can have 1 modal and multiple items can open it.

Example:

```
          <button type="button" data-toggle="modal" data-target="#modal0">Open Modal 1</button>
          <px-modal id="modal0" btn-modal-positive="Continue" btn-modal-negative="Back" modal-heading="Sign-in required">
            <button class="btn btn--primary modal-trigger">Open Modal</button>
            <p>
              <b>Please sign-in to access this part of the application.</b>
            </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
              dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
          </px-modal>
```

**Comment by shalarim** [comment]
Any update on this? I'm experiencing the same issue when using an iron-data-table (based on iron-list).

**Comment by mshahidkhan** [comment]
I switched my modal to paper-dialog ( iron-overlay ).
The way modal works is, it takes parent width/height attributes and expand 100% accordingly.
The key is to use a <div> that is available inside body tag.  You may either inject <div> dynamically or had an empty <div> and inject modal inside it.

Cheers!

**Comment by randyaskin** [comment]
Can this issue be closed?

**Comment by randyaskin** [comment]
Closing due to age / no response.
