### ISSUE TITLE
How to disable "btn-modal-positive" for some validation ?

### ISSUE THREAD

**Issue by Sandip9021** [PredixDev/px-modal#8]
# Submit an Issue

Hi,

## Expected behavior and actual behavior:
I want to disable "btn-modal-positive" to add some validation in the inside modal <textarea> 
How to do that ? 
![image](https://cloud.githubusercontent.com/assets/17237067/17699660/a7bb59a4-63df-11e6-9ce7-3d2c4baee8a8.png)

**Comment by randyaskin** [comment]
In v1.2.7, I've added an attribute called `btn-modal-positive-disabled` that you can add or remove to your `<px-modal ...>` tag for enabling and disabling the positive action button. When you pass the textarea into the contents of the modal, you should be able to specify an onchange or onblur event that points to your validation method, which then adds or removes the attribute.

**Comment by Sandip9021** [comment]
Hi @randyaskin ,
Thanks for your reply.
Can I get some example code for using "btn-modal-positive-disabled",   or any documentation related to "btn-modal-positive-disabled".

Thanks in advance.

**Comment by randyaskin** [comment]
I haven't tested this live, but in your HTML you would have something like:
```
<px-modal btn-modal-positive="Delete" btn-modal-positive-disabled … >
    ...
    <textarea onchange="validate(this)"></textarea>
    ...
</px-modal>
```
and in your JavaScript:
```
validate: function(textarea) {
var length = textarea.value.length,
    disabled = textarea.parentNode.hasAttribute("btn-modal-positive-disabled");
  if(length > 0 && length <= 4000 && disabled) {
    textarea.parentNode.removeAttribute("btn-modal-positive-disabled");
  }
  else {
    textarea.parentNode.addAttribute("btn-modal-positive-disabled");
  }
}
```
Note that depending on how deeply nested your `<textarea>` is compared to the `<px-modal>` tag, you may have to do a bit more DOM traversal than just `parentNode` to get up to the modal tag. You might also be able to access the modal with something like `document.getElementById` (as long as the ID is unique), it's hard to say without seeing your code structure.

Does that help?

**Comment by runn-vermel** [comment]
@Sandip9021 - by passing the element itself as a parameter (just like randy like in the example), you're saving yourself the need to use anything like document.querySelector - which won't work in shadow DOM anyway.
